config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :posts
  resources :matches
  resources :teams

end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:team1_id, :team2_id, :team1_score, :team2_score, :season)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for @match, :html => { :class => "form-horizontal match" } do |f| %>

    <% if @match.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @match.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :team1_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :team1_id, :class => 'form-control' %>
    </div>
    <%= error_span(@match[:team1_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :team2_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :team2_id, :class => 'form-control' %>
    </div>
    <%= error_span(@match[:team2_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :team1_score, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :team1_score, :class => 'form-control' %>
    </div>
    <%= error_span(@match[:team1_score]) %>
  </div>
  <div class="control-group">
    <%= f.label :team2_score, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :team2_score, :class => 'form-control' %>
    </div>
    <%= error_span(@match[:team2_score]) %>
  </div>
  <div class="control-group">
    <%= f.label :season, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :season, :class => 'form-control' %>
    </div>
    <%= error_span(@match[:season]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            matches_path, :class => 'btn btn-default' %>

<% end %>

app/views/matches/edit.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matches/index.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:team1_id) %></th>
      <th><%= model_class.human_attribute_name(:team2_id) %></th>
      <th><%= model_class.human_attribute_name(:team1_score) %></th>
      <th><%= model_class.human_attribute_name(:team2_score) %></th>
      <th><%= model_class.human_attribute_name(:season) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to match.id, match_path(match) %></td>
        <td><%= match.team1_id %></td>
        <td><%= match.team2_id %></td>
        <td><%= match.team1_score %></td>
        <td><%= match.team2_score %></td>
        <td><%= match.season %></td>
        <td><%=l match.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_match_path(match), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      match_path(match),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_match_path,
            :class => 'btn btn-primary' %>

app/views/matches/new.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matches/show.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:team1_id) %>:</strong></dt>
  <dd><%= @match.team1_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team2_id) %>:</strong></dt>
  <dd><%= @match.team2_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team1_score) %>:</strong></dt>
  <dd><%= @match.team1_score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team2_score) %>:</strong></dt>
  <dd><%= @match.team2_score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:season) %>:</strong></dt>
  <dd><%= @match.season %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              matches_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_match_path(@match), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              match_path(@match),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>